name: cls-frontend

services:
  app:
    build: .
    container_name: cls_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
      - NEXT_PUBLIC_TIMEZONE=${NEXT_PUBLIC_TIMEZONE:-America/Toronto}
      - NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${NEXT_PUBLIC_RECAPTCHA_SITE_KEY:-}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "700M"
